[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cell2tcr"
authors = [{name = "Lisa M Dratva", email = "ld21@sanger.ac.uk"}]
readme = "README.md"
dynamic = ["version", "description"]
